# Generated by Django 6.0.5 on 2026-05-21 14:36

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='BlogPost',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=300)),
                ('slug', models.SlugField(unique=True)),
                ('content', models.TextField()),
                ('summary', models.TextField(blank=True, max_length=400)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('published', models.BooleanField(default=False)),
                ('cover_image', models.ImageField(blank=True, null=True, upload_to='blog/')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.DeleteModel(
            name='Introduction',
        ),
        migrations.DeleteModel(
            name='Resume',
        ),
        migrations.AlterModelOptions(
            name='certificate',
            options={'ordering': ['-date_issued']},
        ),
        migrations.AlterModelOptions(
            name='education',
            options={'ordering': ['-start_year']},
        ),
        migrations.AlterModelOptions(
            name='experience',
            options={'ordering': ['-start_date']},
        ),
        migrations.AlterModelOptions(
            name='interest',
            options={'ordering': ['order']},
        ),
        migrations.AlterModelOptions(
            name='project',
            options={'ordering': ['-date']},
        ),
        migrations.AlterModelOptions(
            name='skill',
            options={'ordering': ['order', 'name']},
        ),
        migrations.AlterModelOptions(
            name='sociallink',
            options={'ordering': ['order']},
        ),
        migrations.RenameField(
            model_name='certificate',
            old_name='date',
            new_name='date_issued',
        ),
        migrations.RenameField(
            model_name='education',
            old_name='course',
            new_name='degree',
        ),
        migrations.RenameField(
            model_name='project',
            old_name='github_link',
            new_name='github_url',
        ),
        migrations.RenameField(
            model_name='project',
            old_name='live_link',
            new_name='live_url',
        ),
        migrations.RenameField(
            model_name='sociallink',
            old_name='link',
            new_name='url',
        ),
        migrations.RemoveField(
            model_name='certificate',
            name='certificate_image',
        ),
        migrations.RemoveField(
            model_name='education',
            name='year',
        ),
        migrations.RemoveField(
            model_name='experience',
            name='duration',
        ),
        migrations.RemoveField(
            model_name='project',
            name='technologies',
        ),
        migrations.AddField(
            model_name='certificate',
            name='credential_url',
            field=models.URLField(blank=True),
        ),
        migrations.AddField(
            model_name='certificate',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='certificates/'),
        ),
        migrations.AddField(
            model_name='education',
            name='description',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='education',
            name='end_year',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='education',
            name='field',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AddField(
            model_name='education',
            name='is_current',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='education',
            name='start_year',
            field=models.IntegerField(default=2024),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='experience',
            name='end_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='experience',
            name='is_current',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='experience',
            name='location',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='experience',
            name='start_date',
            field=models.DateField(default=datetime.date(2024, 1, 1)),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='interest',
            name='icon',
            field=models.CharField(blank=True, help_text='Emoji icon', max_length=10),
        ),
        migrations.AddField(
            model_name='interest',
            name='order',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='project',
            name='date',
            field=models.DateField(default=datetime.date(2024, 1, 1)),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='project',
            name='featured',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='project',
            name='tech_stack',
            field=models.CharField(blank=True, help_text='Comma separated', max_length=300),
        ),
        migrations.AddField(
            model_name='skill',
            name='category',
            field=models.CharField(choices=[('language', 'Programming Language'), ('framework', 'Framework / Library'), ('tool', 'Tool / Software'), ('design', 'Design'), ('other', 'Other')], default='other', max_length=20),
        ),
        migrations.AddField(
            model_name='skill',
            name='level',
            field=models.IntegerField(default=80, help_text='Proficiency 0–100'),
        ),
        migrations.AddField(
            model_name='skill',
            name='order',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='sociallink',
            name='display_name',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='sociallink',
            name='order',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='certificate',
            name='details',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='project',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='projects/'),
        ),
        migrations.AlterField(
            model_name='sociallink',
            name='platform',
            field=models.CharField(choices=[('github', 'GitHub'), ('linkedin', 'LinkedIn'), ('behance', 'Behance'), ('twitter', 'Twitter / X'), ('instagram', 'Instagram'), ('youtube', 'YouTube'), ('website', 'Personal Website'), ('other', 'Other')], max_length=20),
        ),
    ]
