# Generated by Django 6.0.5 on 2026-05-24 13:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0002_blogpost_delete_introduction_delete_resume_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='certificate',
            options={},
        ),
        migrations.AlterModelOptions(
            name='project',
            options={},
        ),
        migrations.RemoveField(
            model_name='project',
            name='github_url',
        ),
        migrations.RemoveField(
            model_name='project',
            name='live_url',
        ),
        migrations.RemoveField(
            model_name='project',
            name='tech_stack',
        ),
        migrations.AddField(
            model_name='project',
            name='tech',
            field=models.CharField(default='N/A', max_length=200),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='certificate',
            name='credential_url',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='certificate',
            name='details',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='project',
            name='date',
            field=models.DateField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='project',
            name='image',
            field=models.ImageField(default='N/A', upload_to='projects/'),
            preserve_default=False,
        ),
    ]
